{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $data_array=fetch( 'ezrecommendation', 'recommendation_enable', hash('xmlDataText', $attribute.data_text) )}
{default attribute_base=ContentObjectAttribute}
<input id="ezcoa-{if ne( $attribute_base, 'ContentObjectAttribute' )}{$attribute_base}-{/if}{$attribute.contentclassattribute_id}_{$attribute.contentclass_attribute_identifier}" class="ezcc-{$attribute.object.content_class.identifier} ezcca-{$attribute.object.content_class.identifier}_{$attribute.contentclass_attribute_identifier}" type="checkbox" name="{$attribute_base}_data_recommendation_{$attribute.id}" {if eq( $data_array, 1 )} checked="checked" {/if} value="" />

{/default}


