{* DO NOT EDIT THIS FILE! Use an override template instead. *}

{* This template is meant to be included from the pagelayout, or another global template.
   It will generate an image link to the tracking script that logs a click of a user on the currently displayed
   object (full view).*}

{def $request_url = 'ezreco.gif'|ezimage('no')
     $user_id=fetch( 'user', 'current_user' ).contentobject_id
     $parameters=array()}
{if and( is_set( $content.content_info.object_id), $track )}
    {def $obj=fetch( 'content', 'object', hash( 'object_id', $content.content_info.object_id ) )}

    {foreach $obj.data_map as $attribute}
        {if eq( $attribute.data_type_string, 'ezrecommendation' )}

            {def $data_array=fetch( 'ezrecommendation', 'recommendation_enable', hash( 'xmlDataText', $attribute.data_text ) )}
            {if eq( $data_array, 1 )}

                {set $parameters = generate_html( $content, 'click' )}

                {if ne( $parameters, false() )}
                    {set $request_url = '/ezrecommendation/request'|ezurl( 'no', 'full' )}
                    {set $request_url = concat( $request_url, $parameters )}
                {/if}

                {break}
            {/if}

        {/if}
    {/foreach}
{/if}
<div id="ezrecommendation"></div>
<script type="text/javascript">
    ezreco.img("{$request_url}", {$user_id});
</script>
