{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $data_array=fetch( 'ezrecommendation', 'recommendation_enable', hash('xmlDataText', $attribute.data_text) )}

{$data_array|choose( 'No'|i18n( 'design/standard/content/datatype' ), 'Yes'|i18n( 'design/standard/content/datatype') )}

